### PR TITLE
Next release 3.0.8

### LINKED ISSUE #2319: mrview: ROI edits deleted after two elements drawn
When drawing an ROI, I can draw a maximum of two elements before previously drawn elements start disappearing in a FIFO manner. So if I draw one rectangle, then a second, as soon as I click to draw a third, the first one vanishes. 
This behaviour is limited to the current slice. So for example, if I fill an axial slice, then switch to a saggital slice (which now has a single filled line through it) and begin editing, after 1 edit the filled line will disappear. Switching back to the filled axial slice, just that line is erased, not the whole slice.

This behaviour persists regardless of

- drawing tool (brush / rectangle / fill)
- loading an existing ROI file vs creating a new one within mrview
- drawing or erasing
- single slice or orthoview
- background image

Here is an animation demonstrating the behaviour:
buggyroi

I have never had this problem with any other installations of MRtrix on other machines, only on my new M1 silicon Macbook Pro. I've also checked it isn't just a display issue: if I save the file, quit mrview and load the ROI again, the erased bits are still erased.

**To Reproduce**

1. Open any image in mrview and create a new ROI in the ROI editor
2. Choose a tool (e.g. brush) and click edit
3. Draw a shape
4. Draw another shape
5. Draw a third shape: the first one disappears
6. Draw another shape: the second one disappears
7. You get the picture 

**Platform/Environment/Version**

-  OS: MacOS 11.1
-  *MRtrix3* version `3.0.2-78-g430465d6 64 bit release version, built Mar  9 2021, using Eigen 3.3.9` (built from source)

---

**Advanced debugging information**

-  Qt version: 5.15.2
- OpenGL info:
Screenshot 2021-05-13 at 13 15 27

- `mrview -exit -debug`:

  
```
mrview -exit -debug
mrview: [DEBUG] No config file found at "/etc/mrtrix.conf"
mrview: [INFO] reading config file "/Users/fiona/.mrtrix.conf"...
mrview: [DEBUG] reading key/value file "/Users/fiona/.mrtrix.conf"...
mrview: [INFO] GL renderer:  Apple M1
mrview: [INFO] GL version:   4.1 Metal - 71.0.7
mrview: [INFO] GL vendor:    Apple
mrview: [DEBUG] loading font into OpenGL texture...
mrview: [DEBUG] compiling OpenGL vertex shader:
#version 330 core
layout(location = 0) in vec2 pos;
layout(location = 1) in vec2 font_pos;
uniform float scale_x;
uniform float scale_y;
out vec2 tex_coord;
void main () {
  gl_Position = vec4 (pos[0]*scale_x-1.0, pos[1]*scale_y-1.0, 0.0, 1.0);
  tex_coord = font_pos;
}

mrview: [DEBUG] compiling OpenGL fragment shader:
#version 330 core
in vec2 tex_coord;
uniform sampler2D sampler;
uniform float red, green, blue;
out vec4 color;
void main () {
  color.ra = texture (sampler, tex_coord).rg;
  color.rgb = color.r * vec3 (red, green, blue);
}

mrview: [DEBUG] font loaded
```

### LINKED ISSUE #3142: dwifslpreproc: mrinfo -export_pe_eddy with mif files
MRtrix version 3.0.7

`mrinfo -export_pe_eddy` was changed to work only in conjunction with nii files. dwifslpreproc calls this on a mif file, resulting in an error.

```
dwifslpreproc denoised_degibbsed_ap.mif -se_epi b0_appa.mif denoised_degibbsed_preproc.mif -rpe_pair -pe_dir ap
[...]
Command: mrconvert dwi.mif -strides -1,+2,+3,+4 - | mrinfo - -export_pe_eddy applytopup_config.txt applytopup_indices.txt

dwifslpreproc: [ERROR] mrconvert dwi.mif -strides -1,+2,+3,+4 - | mrinfo - -export_pe_eddy applytopup_config.txt applytopup_indices.txt (dwifslpreproc:828)
dwifslpreproc: [ERROR] Information from failed command:
dwifslpreproc:
               mrconvert: copying from "dwi.mif" to "/Users/pan...18J0L/mrtrix-tmp-AMTUtP.mif"... [==================================================]
               mrinfo: [ERROR] Only export phase encoding table to FSL eddy format in conjunction with MGH / NIfTI format images
```

### LINKED ISSUE #3171: tckglobal: don't invoke get_image() with invalid Header!
**Describe the bug**
I get this bug when I run tckglobal. I am on a mac and have tried using both the HCP and HBN datasets.
```
tckglobal: [INFO] Initialise data structures for global tractography.
tckglobal: [DEBUG] memory-mapping file "/var/folders/rg/wqvgdwpd2jb1b0vpszd5z2w40000gn/T/tmp6_mt2klw/dwi.mif"...
tckglobal: [DEBUG] file "/var/folders/rg/wqvgdwpd2jb1b0vpszd5z2w40000gn/T/tmp6_mt2klw/dwi.mif" mapped at 0x101970000, size 783591408 (read-only)
tckglobal: [DEBUG] image "/var/folders/rg/wqvgdwpd2jb1b0vpszd5z2w40000gn/T/tmp6_mt2klw/dwi.mif" loaded
tckglobal: [DEBUG] image "/var/folders/rg/wqvgdwpd2jb1b0vpszd5z2w40000gn/T/tmp6_mt2klw/dwi.mif" initialised with strides = [ -1 -108 13932 1518588 ], start = 13931, using direct IO
tckglobal: [DEBUG] initialising threads...
tckglobal: [DEBUG] launching 8 threads "loop threads"...
tckglobal: [DEBUG] waiting for completion of threads "loop threads"...
tckglobal: [DEBUG] threads "loop threads" completed OK
tckglobal: [DEBUG] image "/var/folders/rg/wqvgdwpd2jb1b0vpszd5z2w40000gn/T/tmp6_mt2klw/dwi.mif" initialised with strides = [ -129 -13932 1797228 1 ], start = 1797099, using direct IO
tckglobal: [DEBUG] Initialise particle grid.
tckglobal: [DEBUG] unmapping file "/var/folders/rg/wqvgdwpd2jb1b0vpszd5z2w40000gn/T/tmp6_mt2klw/dwi.mif"
tckglobal: [DEBUG] image "/var/folders/rg/wqvgdwpd2jb1b0vpszd5z2w40000gn/T/tmp6_mt2klw/dwi.mif" unloaded
tckglobal: [100%] running MH sampler
tckglobal: [ERROR] FIXME: don't invoke get_image() with invalid Header!
```

**To Reproduce**

The bug can be fully reproduced with this script. It downloads an HBN subject. It is a little more simplified than my initial runs, where I am doing 5tt, but it triggers the same error and is shorter:

```
import os
import subprocess
import tempfile
import nibabel as nib
import numpy as np

from dipy.core.gradients import gradient_table
from dipy.data import fetch_hbn

_, hbn_path = fetch_hbn(subjects=["NDARAV554TP2"])

fname = f"{hbn_path}/derivatives/qsiprep/sub-NDARAV554TP2/ses-HBNsiteRU/dwi/sub-NDARAV554TP2_ses-HBNsiteRU_acq-64dir_space-T1w_desc-preproc_dwi.nii.gz"
fbval = f"{hbn_path}/derivatives/qsiprep/sub-NDARAV554TP2/ses-HBNsiteRU/dwi/sub-NDARAV554TP2_ses-HBNsiteRU_acq-64dir_space-T1w_desc-preproc_dwi.bval"
fbvec = f"{hbn_path}/derivatives/qsiprep/sub-NDARAV554TP2/ses-HBNsiteRU/dwi/sub-NDARAV554TP2_ses-HBNsiteRU_acq-64dir_space-T1w_desc-preproc_dwi.bvec"

img = nib.load(fname)
gtab = gradient_table(fbval, fbvec)
data = img.get_fdata(dtype=np.float32)
affine = img.affine

tmp_dir = tempfile.mkdtemp()

dwi_file = os.path.join(tmp_dir, "dwi.nii.gz")
dwi_mif = os.path.join(tmp_dir, "dwi.mif")
nib.save(nib.Nifti1Image(data, affine), dwi_file)

subprocess.run([
    "mrconvert", dwi_file, dwi_mif,
    "-fslgrad", fbvec, fbval], check=True)

wm_response = os.path.join(tmp_dir, "wm_response.txt")
gm_response = os.path.join(tmp_dir, "gm_response.txt")
csf_response = os.path.join(tmp_dir, "csf_response.txt")

subprocess.run([
    "dwi2response", "dhollander", dwi_mif,
    wm_response, gm_response, csf_response])

global_file = os.path.join(tmp_dir, "tracks.tck")
fod_file = os.path.join(tmp_dir, "fod.mif")

cmd = [
    "tckglobal",
    dwi_mif,
    wm_response,
    "-riso", csf_response,
    "-riso", gm_response,
    "-niter", str(int(1e9)),
    "-fod", fod_file,
    "-debug",
    global_file,
]

subprocess.run(
    cmd, check=True)
```

**Platform/Environment/Version**

macOS 15.5

== mrinfo 3.0.7 ==
64 bit release version, built Jul 26 2025, using Eigen 3.4.0

Best,
    John

### PR DESCRIPTION
**Pull request by jdtournier**
#### Bug fixes

- [avatar for Lestropie](https://github.com/Lestropie) [avatar for jdtournier](https://github.com/jdtournier) [tckglobal: Fix operation](https://github.com/MRtrix3/mrtrix3/pull/3172) following changes made as part of #3011 resulting in multiple attempts to construct an Image class from the same input header. Fixes #3171. 
  
  Also fix several race conditions identified using thread sanitiser.
    
- [avatar for jdtournier](https://github.com/jdtournier) [Fix race condition in ThreadedLoop](https://github.com/MRtrix3/mrtrix3/pull/3215). Issue identified by thread sanitizer while working on #3172.

- [avatar for Lestropie](https://github.com/Lestropie) [tcksift2: Minor fixes to diagnosis data](https://github.com/MRtrix3/mrtrix3/pull/3050): the current `DWI::Fixel_map<>` class (to be deprecated in the future) contains at index 0 a fixel with an empty constructor. Any diagnosis information presented to the user should therefore be computed without consideration for this non-existing fixel.    Reported by @ppruc.

- [avatar for Lestropie](https://github.com/Lestropie) [fsl.check_first(): Handle run_first_all providing no HOLDID](https://github.com/MRtrix3/mrtrix3/pull/3176): follows #2609. Hopefully addresses [issue reported on forum](https://community.mrtrix.org/t/5ttgen-fsl-error-for-run-first/8527).

- [avatar for Lestropie](https://github.com/Lestropie) [MR::Axes::permutations_type: Fix is_identity()](https://github.com/MRtrix3/mrtrix3/pull/3169).

- [avatar for Lestropie](https://github.com/Lestropie) [Fix phase encoding handling on 3.0.7](https://github.com/MRtrix3/mrtrix3/pull/3146). Fixes #3142. 

- [avatar for Lestropie](https://github.com/Lestropie) [mrmath: Typo in error message](https://github.com/MRtrix3/mrtrix3/pull/3150) 

#### MRView

- [avatar for Lestropie](https://github.com/Lestropie) [mrview: Bugfix in rendering of cubes in connectome tool](https://github.com/MRtrix3/mrtrix3/pull/3204): problem introduced in 92eee2a39948dc5022ea46f62ada65a4631b58c8 as part of #283.

- [avatar for daljit46](https://github.com/daljit46) [Fix tractography rendering performance on macOS](https://github.com/MRtrix3/mrtrix3/pull/3197): this PR fixes the longstanding performance issues in the viewer on macOS when visualising tractography streamlines (using pseudotubes). 

- [avatar for daljit46](https://github.com/daljit46) [Fix ROI edits disappearing on MacOS](https://github.com/MRtrix3/mrtrix3/pull/3195): this small change fixes #2319.

#### Documentation
    
- [avatar for Lestropie](https://github.com/Lestropie) [Docs: Description of options with single-shell data](https://github.com/MRtrix3/mrtrix3/pull/3198): replacement of #2441, targeting `master`.

- [avatar for Lestropie](https://github.com/Lestropie) [Stats commands: Clarify non-stationarity correction in help pages](https://github.com/MRtrix3/mrtrix3/pull/3187).

- [avatar for Lestropie](https://github.com/Lestropie) [tcksift2 & afdconnectivity: Update citation](https://github.com/MRtrix3/mrtrix3/pull/3205).

- [avatar for Lestropie](https://github.com/Lestropie) [tck2connectome: Add default assignment mechanism to docs](https://github.com/MRtrix3/mrtrix3/pull/3181), as [requested on forum](https://community.mrtrix.org/t/tck2connctome-default-settings/8542).

#### Enhancements

- [avatar for Lestropie](https://github.com/Lestropie) [DICOM: Performance fix to wildcard matching](https://github.com/MRtrix3/mrtrix3/pull/3208).

- [avatar for Lestropie](https://github.com/Lestropie) [mesh2voxel: Accept >3D image as template voxel grid](https://github.com/MRtrix3/mrtrix3/pull/3107): simple change to reduce the template voxel grid image to 3D if the image provided by the user is > 3D.

- [avatar for Lestropie](https://github.com/Lestropie) [Pipe image format: Revise error message](https://github.com/MRtrix3/mrtrix3/pull/3154).

#### Build-related issues

- [avatar for bjeurissen](https://github.com/bjeurissen) [Update configure script for Xcode26 compatibility](https://github.com/MRtrix3/mrtrix3/pull/3202): link against OpenGL only, not AGL as it is no longer included in MacOS Tahoe/Xcode26 (https://bugreports.qt.io/browse/QTBUG-137687).

- [avatar for daljit46](https://github.com/daljit46) [Fix Eigen 3.4.1 type mismatch in `ColourMap` clamping](https://github.com/MRtrix3/mrtrix3/pull/3207): fix compilation error leading to `Eigen::internal::traits<double>` errors.
    
- [avatar for Lestropie](https://github.com/Lestropie) [mrcalc: Docs: Combining mag&phase into complex data](https://github.com/MRtrix3/mrtrix3/pull/3148): caught myself feeling the need to demonstrate this to a colleague and realised that it really should be an example usage.

- [avatar for Lestropie](https://github.com/Lestropie) [Testing: Relax tolerances on fixelcfestats tests](https://github.com/MRtrix3/mrtrix3/pull/3149): tests were observed to fail on MacOS in #3146.

### CODE REVIEW

**Comment by jdtournier** [comment]
@daljit46: seems we have build failures for both macOS release 3.0.8 packages ([native](https://github.com/MRtrix3/mrtrix3/actions/runs/18656865098) and [anaconda](https://github.com/MRtrix3/mrtrix3/actions/runs/18656865110)). Any chance you could investigate? 

@bjeurissen, maybe you have an idea what the issue is with the native build...?
