### ISSUE TITLE
Zooming and ODF rendering broken on Mac

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#397]
Both on (latest) master branch, as well as on updated syntax branch.  As originally reported by @dchristiaens in https://github.com/MRtrix3/mrtrix3/pull/225#issuecomment-153653893 .

**Comment by jdtournier** [comment]
Any idea which commit caused the problem? Probably simplest to track down on the master branch. My money is on 231ab0cc - that changed a fair bit with the OpenGL handling, most likely to have caused problems...

**Comment by dchristiaens** [comment]
OK, finally got some time to look into this. I have some trouble zooming in or out with apple's magic mouse from time to time; not with an old-fashioned scroll wheel. I have the feeling it used to be better, but I've not yet traced this back to its origins. By any chance, is there a keyboard shortcut for zooming in or out? That might come in as a handy alternative at times...

A more pressing issue is the ODF rendering. Here's a screenshot in the current master branch:
![screen shot 2015-11-16 at 13 21 51](https://cloud.githubusercontent.com/assets/7466983/11184456/fa60db2e-8c77-11e5-864e-4c9853aaf737.png)
I'm not sure what's going on with the ODFs. Notice that the intensity bar in the lower right corner looks weird too. I was able to track this one down to commit e9a0dac and pull request #266. That means it's been around since June and I really need to update more often :-)

**Comment by dchristiaens** [comment]
Specifically, the Mac OS X rendering issue was introduced in b2f4ca9, the very first commit in this pull request. Subsequent commits did not fix it.

**Comment by jdtournier** [comment]
OK, for a minute I thought it sounded similar to [the funny transparency issue](https://github.com/MRtrix3/mrtrix3/pull/266#issuecomment-110714924) we had with this branch, but if you say the problem was introduced earlier, then I'm not so sure. All this commit did was change the code responsible for requesting an OpenGL core profile from requesting it per-context, to setting it once application-wide. Is there any difference in the OpenGL attributes reported in the Help->OpenGL dialog...?

**Comment by jdtournier** [comment]
As to scrolling going funny, 3ed77660 is the commit most likely to have introduced problems - although it was supposed to help...

Regarding zooming: I'd added support for pinch to zoom a while back in commit fc6013af, although I haven't really had a chance to test it out thoroughly (won't work on my Linux laptop. unfortunately). Does this not work...?

**Comment by jdtournier** [comment]
One more comment: I had to add keyboard shortcuts for zooming in the previous version (0.2.x) of MRView for precisely this reason. More than happy to add them back in, just haven't gotten round to it yet...

**Comment by dchristiaens** [comment]
OpenGL dialogs before (7bc5420) and after pull request #266 (e9a0dac):

Before:
![screen shot 2015-11-16 at 16 35 51](https://cloud.githubusercontent.com/assets/7466983/11186079/49048d2c-8c80-11e5-9d80-e74af6c99e2a.png)

After:
![screen shot 2015-11-16 at 16 37 35](https://cloud.githubusercontent.com/assets/7466983/11186085/4e0b83fc-8c80-11e5-9b39-f52b626b4c74.png)

Difference appears to be in the transparency indeed. I'm a bit of a noob in this area though...

**Comment by jdtournier** [comment]
Thanks, Daan, that's actually really helpful. Would explain a few things... Also the fact that you have an ATI card might explain why this hasn't been picked up before by other Mac users - I find ATI card have a few quirks all of their own... Can I just check whether you have `NeedOpenGLCoreProfile: 0` in your `~/.mrtrix.conf` file, and whether your volume render mode works as expected?

I'll see if I can request a context with no alpha channel (we don't need it).

**Comment by dchristiaens** [comment]
Regarding the zoom: Yes, 3ed7766 is where it breaks down. Before, zooming worked really nice and smooth for me. With that particular commit, it works in (too) bit steps and appears to "lag behind" (slow response time).

I don't have a trackpad right now, but I'll give it a test drive when I get my hands on a laptop.

**Comment by jdtournier** [comment]
Does the `fix_mrview_alpha_channel` branch fix the ODF render issue for you...?

**Comment by dchristiaens** [comment]
I do not have `NeedOpenGLCoreProfile: 0` in my config. When I do, I mrview doesn't launch. It gives the following error message and a dialog box opens up saying "mrview quit unexpectedly".
```
2015-11-16 16:56:17.597 mrview[86217:303] invalid drawable
mrview: [WARNING] unable to determine OpenGL version - operation may be unstable if actual version is less than 3.3
mrview: [ERROR] GLSL log [vertex shader]: ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:1: '' : syntax error #version
ERROR: 0:2: 'layout' : syntax error syntax error

Segmentation fault
```
The first line, by the way, I get all the time.

Volume rendering works fine, also with different alpha values. 
![screen shot 2015-11-16 at 17 02 51](https://cloud.githubusercontent.com/assets/7466983/11186812/d9a1fae2-8c83-11e5-8825-f9c30ba97e0e.png)

(all of this was tested in the current master, 7cc6847)

**Comment by jdtournier** [comment]
Good - all as it should be...

**Comment by dchristiaens** [comment]
The `fix_mrview_alpha_channel` works like a charm. Thanks Donald, you're a genius!

I'm guessing this should be tested on a few more systems before merge?

**Comment by jdtournier** [comment]
Works fine on my Arch laptop with a NVidia card. But we'll need to create a pull request for it anyway... 

I'll try and integrate a few changes to the scroll handling before we do this though... :wink:

**Comment by dchristiaens** [comment]
Excellent, let me know if you need any assistance. Thanks for the rapid fix!

**Comment by jdtournier** [comment]
@dchristiaens, can you add these lines to your `src/gui/mrview/window.cpp`, and report back what it says in the terminal when you try to scroll...?

~~~~C++
1496                 VAR (event->source());                                                                                                                             
1497                 VAR (event->delta());                                                                                                                              
1498                 // these will only compile on Qt >= 5.4:                                                                                                           
1499                 VAR (event->pixelDelta());                                                                                                                         
1500                 VAR (event->angleDelta());                                                                                                                         
~~~~

**Comment by jdtournier** [comment]
Sorry, that should be:

~~~C++
1496                 VAR (event->source());                                                                                                                             
1497                 VAR (event->delta());                                                                                                                              
1498                 // these will only compile on Qt >= 5.4:                                                                                                           
1499                 VAR (event->pixelDelta().y());                                                                                                                     
1500                 VAR (event->angleDelta().y());                                                                                                                     
~~~

**Comment by dchristiaens** [comment]
Doesn't compile. I get:
```
src/gui/mrview/window.cpp:1496:31: error: no member named 'source' in 'QWheelEvent'
                  VAR (event->source());                                                                                                                             
                       ~~~~~  ^
lib/debug.h:49:106: note: expanded from macro 'VAR'
  std::cerr << MR::App::NAME << " [" << __FILE__  << ": " << __LINE__ << "]: " << #variable << " = " << (variable) << "\n";
                                                                                                         ^
1 error generated.
```
already on the first line. I'm running Qt 5.2.0, but happy to update if you need it.

**Comment by dchristiaens** [comment]
Just to be sure, I added them within context:
```
            if (buttons_ == Qt::NoButton) {

              if (modifiers_ == Qt::ControlModifier) {
                  VAR (event->source());                                                                                                                             
                  VAR (event->delta());                                                                                                                              
                  // these will only compile on Qt >= 5.4:                                                                                                           
                  //VAR (event->pixelDelta().y());                                                                                                                     
                  //VAR (event->angleDelta().y());
                set_FOV (FOV() * std::exp (-0.1*delta.y()));
                glarea->update();
                event->accept();
                return;
              }
```
Is that where you want it to be?

**Comment by jdtournier** [comment]
Ah, you're on 5.2. That changes a few things... I was looking at the 5.4+ codepath, which is quite different. Don't worry, looks like it's a different problem then... I'll chase up with something else.

**Comment by jdtournier** [comment]
@dchristiaens: from what you say, the issue is probably just that scroll values were being cast to integer multiples of 120. I just pushed a commit to address this on the `fix_mrview_alpha_channel` branch, see if that helps.

**Comment by dchristiaens** [comment]
Works perfectly. Thanks again for the great support!

**Comment by jdtournier** [comment]
:yum: it's nice when things work out like this...

I'll try adding shortcuts for zooming in & out, as for the previous version. Probably map to Home & End - is there a standard shortcut for this? The closest I can think of is `Ctrl -/+` (as per GIMP and others), but I find that a bit unwieldy...

**Comment by dchristiaens** [comment]
I'm in favour of keyboard shortcuts for everything, particularly for the large array of mice/trackpads out there. I used to have a dedicated MRtrix mouse, of the kind that still had a cable ;-)

`Ctrl +/-` and `Cmd +/-` are fairly standard, I suppose, which makes them easy to find. I'm happy with Home/End too, if that's what you prefer. We just need to document it on the wiki...

**Comment by jdtournier** [comment]
OK, shortcuts added and mapped to `Ctrl +/-` - hopefully will map to `Cmd +/-` on the mac...
I'll submit a pull request for all this in a minute.

**Comment by jdtournier** [comment]
By the way, these shortcuts show up in the menu next to the corresponding entry, they're self-documenting... :wink: 

But you're right, we'll need to set up an MRView cheat sheet at some point, as per #308...

**Comment by dchristiaens** [comment]
Awesome! Good idea to have them them in the menu too. And yes, they map to `Cmd +/-` on Mac.

**Comment by jdtournier** [comment]
Good. I'll close this issue and start a pull request for all this.
